#ifndef _ALTERA_HPS_H_
#define _ALTERA_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '/cygdrive/c/Users/akash/Desktop/FPGA_Projects/QKD/qkd_shift_register_test/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'shift_reg_mm', class 'shift_reg_mm'
 * The macros are prefixed with 'SHIFT_REG_MM_'.
 * The prefix is the slave descriptor.
 */
#define SHIFT_REG_MM_COMPONENT_TYPE shift_reg_mm
#define SHIFT_REG_MM_COMPONENT_NAME shift_reg_mm
#define SHIFT_REG_MM_BASE 0x0
#define SHIFT_REG_MM_SPAN 8
#define SHIFT_REG_MM_END 0x7

/*
 * Macros for device 'shift_reg_mm_1', class 'shift_reg_mm'
 * The macros are prefixed with 'SHIFT_REG_MM_1_'.
 * The prefix is the slave descriptor.
 */
#define SHIFT_REG_MM_1_COMPONENT_TYPE shift_reg_mm
#define SHIFT_REG_MM_1_COMPONENT_NAME shift_reg_mm_1
#define SHIFT_REG_MM_1_BASE 0x8
#define SHIFT_REG_MM_1_SPAN 8
#define SHIFT_REG_MM_1_END 0xf


#endif /* _ALTERA_HPS_H_ */
